from collections.abc import Sequence
import mlx.core as mx
from .transforms import BboxBase

def affine_transform(points: mx.array, trans: mx.array) -> mx.array: ...
def count_bboxes_overlapping_bbox(bbox: BboxBase, bboxes: Sequence[BboxBase]) -> int: ...
