from collections.abc import Sequence
import matplotlib._mlx_array as mlxarr
from .transforms import BboxBase

def affine_transform(points: mlxarr.ndarray, trans: mlxarr.ndarray) -> mlxarr.ndarray: ...
def count_bboxes_overlapping_bbox(bbox: BboxBase, bboxes: Sequence[BboxBase]) -> int: ...
