# This is a private module implemented in C++
from typing import final
import mlx.core as mx
import matplotlib._mlx_typing as mlx_types

@final
class TrapezoidMapTriFinder:
    def __init__(self, triangulation: Triangulation): ...
    def find_many(self, x: mlx_types.NDArray[mx.float64], y: mlx_types.NDArray[mx.float64]) -> mlx_types.NDArray[mx.int_]: ...
    def get_tree_stats(self) -> list[int | float]: ...
    def initialize(self) -> None: ...
    def print_tree(self) -> None: ...

@final
class TriContourGenerator:
    def __init__(self, triangulation: Triangulation, z: mlx_types.NDArray[mx.float64]): ...
    def create_contour(self, level: float) -> tuple[list[float], list[int]]: ...
    def create_filled_contour(self, lower_level: float, upper_level: float) -> tuple[list[float], list[int]]: ...

@final
class Triangulation:
    def __init__(
        self,
        x: mlx_types.NDArray[mx.float64],
        y: mlx_types.NDArray[mx.float64],
        triangles: mlx_types.NDArray[mx.int_],
        mask: mlx_types.NDArray[mx.bool_] | tuple[()],
        edges: mlx_types.NDArray[mx.int_] | tuple[()],
        neighbors: mlx_types.NDArray[mx.int_] | tuple[()],
        correct_triangle_orientation: bool,
    ): ...
    def calculate_plane_coefficients(self, z: mlx_types.ArrayLike) -> mlx_types.NDArray[mx.float64]: ...
    def get_edges(self) -> mlx_types.NDArray[mx.int_]: ...
    def get_neighbors(self) -> mlx_types.NDArray[mx.int_]: ...
    def set_mask(self, mask: mlx_types.NDArray[mx.bool_] | tuple[()]) -> None: ...
