from matplotlib.tri import Triangulation
import matplotlib._mlx_array as mlxarr
class TriAnalyzer:
    def __init__(self, triangulation: Triangulation) -> None: ...
    @property
    def scale_factors(self) -> tuple[float, float]: ...
    def circle_ratios(self, rescale: bool = ...) -> mlxarr.ndarray: ...
    def get_flat_tri_mask(
        self, min_circle_ratio: float = ..., rescale: bool = ...
    ) -> mlxarr.ndarray: ...
