from matplotlib.tri import Triangulation
import mlx.core as mx
class TriAnalyzer:
    def __init__(self, triangulation: Triangulation) -> None: ...
    @property
    def scale_factors(self) -> tuple[float, float]: ...
    def circle_ratios(self, rescale: bool = ...) -> mx.array: ...
    def get_flat_tri_mask(
        self, min_circle_ratio: float = ..., rescale: bool = ...
    ) -> mx.array: ...
